In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("raw_data.csv")

In [3]:
data['Period']=pd.to_datetime(data.Period)

In [4]:
new_data = pd.DataFrame(pd.date_range(data.Period[0],data.Period[98],freq='d'),columns = ['Period'])

In [5]:
def convert_df(df, column):
    ret_lis = []
    for i in range(len(df)-1):
        ret_lis = ret_lis + list(np.linspace(df[column][i], df[column][i+1],
                                             num=df[["Period"]].Period[i].days_in_month+1))[:-1]
    return ret_lis + [df[column].values[-1]]

In [6]:
for col in data.columns.drop('Period'):
    new_data[col] = convert_df(data,col)

In [7]:
new_data

,Period,Inflation (Can),Inflation (US),GDP (B$),Empl.Per. (M),CPI (Can),CPI (US),CC (Can),PC Util (Can),PC Util (US),...,Bus Conf (US),TSX,Retail YoY%,M3 T$,Gov Sp M$,EI (000s),Disp.Inc. M$,Consum.Cr. M$,Exports M$,Tourist Arr. (Persons)
0,2013-01-01,0.500000,1.600000,1729.586000,17.508000,121.300000,231.679000,53.900000,80.400000,76.700000,...,3.280000,12572.000000,1.400000,1.601576,127154.000000,5.390500e+05,343000.000000,605665.000000,38594.100000,1.215381e+06
1,2013-01-02,0.522581,1.612903,1729.754355,17.509477,121.345161,231.719581,53.951613,80.409677,76.709677,...,3.277419,12577.451613,1.429032,1.602049,127149.451613,5.388694e+05,343077.838710,605801.774194,38623.038710,1.215621e+06
2,2013-01-03,0.545161,1.625806,1729.922710,17.510955,121.390323,231.760161,54.003226,80.419355,76.719355,...,3.274839,12582.903226,1.458065,1.602523,127144.903226,5.386887e+05,343155.677419,605938.548387,38651.977419,1.215862e+06
3,2013-01-04,0.567742,1.638710,1730.091065,17.512432,121.435484,231.800742,54.054839,80.429032,76.729032,...,3.272258,12588.354839,1.487097,1.602996,127140.354839,5.385081e+05,343233.516129,606075.322581,38680.916129,1.216102e+06
4,2013-01-05,0.590323,1.651613,1730.259419,17.513910,121.480645,231.841323,54.106452,80.438710,76.738710,...,3.269677,12593.806452,1.516129,1.603469,127135.806452,5.383274e+05,343311.354839,606212.096774,38709.854839,1.216343e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2977,2021-02-25,2.042857,2.471429,1982.181571,18.791000,139.500000,264.559857,49.728571,81.600000,74.414286,...,24.110000,18146.714286,22.271429,2.967031,148020.571429,1.484080e+06,480320.428571,786880.428571,50582.942857,1.204504e+05
2978,2021-02-26,2.082143,2.503571,1983.111929,18.801825,139.525000,264.618143,49.871429,81.625000,74.485714,...,25.225000,18172.535714,22.928571,2.966793,148040.178571,1.481390e+06,480447.071429,786925.071429,50599.382143,1.212336e+05
2979,2021-02-27,2.121429,2.535714,1984.042286,18.812650,139.550000,264.676429,50.014286,81.650000,74.557143,...,26.340000,18198.357143,23.585714,2.966555,148059.785714,1.478700e+06,480573.714286,786969.714286,50615.821429,1.220167e+05
2980,2021-02-28,2.160714,2.567857,1984.972643,18.823475,139.575000,264.734714,50.157143,81.675000,74.628571,...,27.455000,18224.178571,24.242857,2.966317,148079.392857,1.476010e+06,480700.357143,787014.357143,50632.260714,1.227999e+05
2981,2021-03-01,2.200000,2.600000,1985.903000,18.834300,139.600000,264.793000,50.300000,81.700000,74.700000,...,28.570000,18250.000000,24.900000,2.966079,148099.000000,1.473320e+06,480827.000000,787059.000000,50648.700000,1.235830e+05

In [10]:
new_data.to_csv("converted.csv",index=False)